apiVersion: v1
kind: Pod
metadata:
  name: test-logger-1
  namespace: test
spec:
  containers:
    - name: logger
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - while true; do echo "[$(date)] This is a test log 1 line from stdout"; sleep 5; done
      resources:
        limits:
          memory: "64Mi"
          cpu: "100m"
